package com.cell.user.dao.entiy;

import java.util.Date;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.id
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.customer_id
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private String customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.name
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.description
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.state
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private Byte state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.type
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.created_time
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.created_by
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.updated_time
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private Date updatedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.updated_by
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private String updatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.deleted_time
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private Date deletedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.deleted_by
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private String deletedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.deleted
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private Boolean deleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.DataChange_LastTime
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	private Date datachangeLasttime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.id
	 * @return  the value of role.id
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.id
	 * @param id  the value for role.id
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.customer_id
	 * @return  the value of role.customer_id
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public String getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.customer_id
	 * @param customerId  the value for role.customer_id
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setCustomerId(String customerId) {
		this.customerId = customerId == null ? null : customerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.name
	 * @return  the value of role.name
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.name
	 * @param name  the value for role.name
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.description
	 * @return  the value of role.description
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.description
	 * @param description  the value for role.description
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.state
	 * @return  the value of role.state
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.state
	 * @param state  the value for role.state
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setState(Byte state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.type
	 * @return  the value of role.type
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.type
	 * @param type  the value for role.type
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.created_time
	 * @return  the value of role.created_time
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.created_time
	 * @param createdTime  the value for role.created_time
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.created_by
	 * @return  the value of role.created_by
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.created_by
	 * @param createdBy  the value for role.created_by
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy == null ? null : createdBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.updated_time
	 * @return  the value of role.updated_time
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public Date getUpdatedTime() {
		return updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.updated_time
	 * @param updatedTime  the value for role.updated_time
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.updated_by
	 * @return  the value of role.updated_by
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public String getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.updated_by
	 * @param updatedBy  the value for role.updated_by
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy == null ? null : updatedBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.deleted_time
	 * @return  the value of role.deleted_time
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public Date getDeletedTime() {
		return deletedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.deleted_time
	 * @param deletedTime  the value for role.deleted_time
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setDeletedTime(Date deletedTime) {
		this.deletedTime = deletedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.deleted_by
	 * @return  the value of role.deleted_by
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public String getDeletedBy() {
		return deletedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.deleted_by
	 * @param deletedBy  the value for role.deleted_by
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setDeletedBy(String deletedBy) {
		this.deletedBy = deletedBy == null ? null : deletedBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.deleted
	 * @return  the value of role.deleted
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public Boolean getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.deleted
	 * @param deleted  the value for role.deleted
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.DataChange_LastTime
	 * @return  the value of role.DataChange_LastTime
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public Date getDatachangeLasttime() {
		return datachangeLasttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.DataChange_LastTime
	 * @param datachangeLasttime  the value for role.DataChange_LastTime
	 * @mbggenerated  Mon Mar 06 10:01:56 CST 2017
	 */
	public void setDatachangeLasttime(Date datachangeLasttime) {
		this.datachangeLasttime = datachangeLasttime;
	}
}